all:
	@echo "Choose an option"

Ex1: Ex1/Ex1.ino
	../../arduino compile --fqbn arduino:avr:uno Ex1
	../../arduino upload -p /dev/ttyACM0 --fqbn arduino:avr:uno Ex1

Ex2: Ex2/Ex2.ino
	../../arduino compile --fqbn arduino:avr:uno Ex2
	../../arduino upload -p /dev/ttyACM0 --fqbn arduino:avr:uno Ex2
	screen /dev/ttyAMC0 115200

Ex3: Ex3/Ex3.ino
	../../arduino compile --fqbn arduino:avr:uno Ex3
	../../arduino upload -p /dev/ttyACM0 --fqbn arduino:avr:uno Ex3

Ex4: Ex4/Ex4.ino
	../../arduino compile --fqbn arduino:avr:uno Ex4
	../../arduino upload -p /dev/ttyACM0 --fqbn arduino:avr:uno Ex4

Ex5: Ex5/Ex5.ino
	../../arduino compile --fqbn arduino:avr:uno Ex5
	../../arduino upload -p /dev/ttyACM0 --fqbn arduino:avr:uno Ex5

Ex6: Ex6/Ex6.ino
	../../arduino compile --fqbn arduino:avr:uno Ex6
	../../arduino upload -p /dev/ttyACM0 --fqbn arduino:avr:uno Ex6
